module.exports = [
    {
        id: "1",
        name: "5 Audience Left",
        hostname: "192.168.32.29",
        port: 8080,
        username: "onvif",
        password: "1234",
        presetLocks: [
            "000",
            "001",
            "002",
            "003",
            "004",
        ],
        whiteBalance: {mode: "MANUAL", red: 22, blue: 128},
        snapshotUrl: "",
    },
    {
        id: "2",
        name: "6 Audience Center",
        hostname: "192.168.32.30",
        port: 8080,
        username: "onvif",
        password: "1234",
        presetLocks: [
            "preset000",
            "preset001",
            "preset002",
            "preset003",
            "preset004",
        ],
        whiteBalance: {mode: "MANUAL", red: 16, blue: 128},
        snapshotUrl: "",
    },
    {
        id: "3",
        name: "7 Audience Right",
        hostname: "192.168.32.31",
        port: 8080,
        username: "onvif",
        password: "1234",
        presetLocks: [
            "000",
            "001",
            "002",
            "003",
            "004",
        ],
        whiteBalance: {mode: "MANUAL", red: 16, blue: 128},
        snapshotUrl: "",
    }
];